modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="vmcraft_ii"
version="2.0.0"
displayName="VMCraft-II"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Hunter Casteel, Cade Disselkoan, Heba Aljabrine"
description='''
Connect to virtual machines hosted on a Proxmox server from within Minecraft!
'''

[[dependencies.vmcraft_ii]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




